apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1 # Interessante deixar 1 para não obter multiplos bancos
  minReadySeconds: 10 # tempo minimo para o conteiner estar pronto
  template:
    metadata:
      labels: # rótulo
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10 #Tempo para finalizar conteiner
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dados
              key: DB_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_PASSWORD
              
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumeMounts: # Esta ligando o volume para dentro do nosso container
        - name: mysql-ps
          mountPath: /var/lib/mysql
        volumes:
      volumes:
        - name: mysql-ps # o nome precisa ser igual do VolumeMount
        persistentVolumeClaim:
          claimName: volume-mysql # Vamos em "Volum.yaml" para descobrir nosso nome