apiVersion: v1
kind: Service
metadata:
  name: nodeport-api
spec:
  type: NodePort
  selector:
  #é o serviço que vai estar preso a qual aplicação, podemos pegar essa junção pelo
  # arquivo deploy da aplicação: metadata.labels.app.vollmed
    app: vollmed
  ports:
    - port: 3000
      targetPort: 3000    
      nodePort: 3007