apiVersion: apps/v1
kind: Deployment
metadata:
  name: vollmed
  labels:
    app: vollmed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vollmed
  template:
    metadata:
      labels:
        app: vollmed
    spec:
      containers:
      - name: vollmedAPI
        image: leoardosartorello/vollmed:v8
        ports:
        - containerPort: 3000
        env:
        # Define the environment variable
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dados
              key: DB_HOST
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dados
              key: DB_DATABASE
        - name: DB_PASSWORD
          valueFrom:
            secretsKeyRef:
              name: dados
              key: DB_PASSWORD
